service: McDrink
app: mc-drink

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    CHROME_PATH: "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"

functions:
  app:
    handler: handler.handler
