service: McDrink
app: mc-drink

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  stage: dev

plugins:
  - serverless-offline
  - serverless-iam-roles-per-function

functions:
  telegramBot:
    handler: handler.telegramBot
    events:
      - http:
          path: telegram
          method: ANY
          cors: true
    environment:
      BOT_TOKEN: ${file(./secrets/secrets.yml):BOT_TOKEN}
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - lambda:InvokeFunction
          - lambda:InvokeAsync
        Resource: "*"
  telegramApi:
    handler: handler.telegramApi
    timeout: 900
    environment:
      BOT_TOKEN: ${file(./secrets/secrets.yml):BOT_TOKEN}
      CHROME_PATH: ${file(./secrets/secrets.yml):CHROME_PATH}
      CAPTCHA_KEY: ${file(./secrets/secrets.yml):CAPTCHA_KEY}
